version: '3'

services:
  db:
    # this image already has databases, users, and max prepared statement configured
    image: lleseigneur/bonita-postgres:11-alpine
    environment: 
    - POSTGRES_PASSWORD=postgres
    restart: always
  bonita:
    image: bonita
    ports:
    - 8080:8080
    environment:
    - POSTGRES_ENV_POSTGRES_PASSWORD=postgres
    - DB_VENDOR=postgres
    - DB_HOST=db
    - DB_NAME=bonita
    - DB_USER=bonita
    - DB_PASS=bpm
    - BIZ_DB_NAME=business_data
    - BIZ_DB-USER=business_data
    - BIZ_DB_PASS=bpm
    - TENANT_LOGIN=tech_user
    - TENANT_PASSWORD=secret
    - PLATFORM_LOGIN=pfadmin
    - PLATFORM_PASSWORD=pfsecret
    restart: on-failure:2
    depends_on:
    - db
    entrypoint:
    - bash
    - -c
    - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh